const blog_data = [{
        id: 1,
        title: "The Future of Artificial Intelligence",
        description: "Discover how AI is transforming industries and changing the way we work every day.",
        category: "Technology",
        image: "",
        author: { name: "Admin", username: "admin", profile: "" },
        stats: { likes: 245, comments: 18, views: "2.4K" },
        readTime: "5 min read",
        createdAt: "05 Aug 2026"
    },
    {
        id: 2,
        title: "10 Places You Must Visit This Year",
        description: "Explore breathtaking destinations around the world with unforgettable experiences.",
        category: "Travel",
        image: "",
        author: { name: "Olivia", username: "olivia", profile: "" },
        stats: { likes: 198, comments: 14, views: "1.8K" },
        readTime: "7 min read",
        createdAt: "04 Aug 2026"
    },
    {
        id: 3,
        title: "Why Vinyl Records Are Trending Again",
        description: "Music lovers are returning to vinyl because of its unique analog sound experience.",
        category: "Music",
        image: "",
        author: { name: "Ethan", username: "ethan", profile: "" },
        stats: { likes: 324, comments: 39, views: "3.2K" },
        readTime: "4 min read",
        createdAt: "03 Aug 2026"
    },
    {
        id: 4,
        title: "Startup Ideas That Could Succeed",
        description: "Looking for your next startup? These ideas solve real-world problems.",
        category: "Business",
        image: "",
        author: { name: "Sophia", username: "sophia", profile: "" },
        stats: { likes: 289, comments: 26, views: "2.7K" },
        readTime: "6 min read",
        createdAt: "02 Aug 2026"
    },
    {
        id: 5,
        title: "Best Multiplayer Games of 2026",
        description: "Discover the multiplayer games dominating the gaming community this year.",
        category: "Gaming",
        image: "",
        author: { name: "Noah", username: "noah", profile: "" },
        stats: { likes: 412, comments: 61, views: "4.6K" },
        readTime: "8 min read",
        createdAt: "01 Aug 2026"
    },
    {
        id: 6,
        title: "Healthy Habits for a Better Life",
        description: "Simple daily habits that improve physical and mental well-being.",
        category: "Health",
        image: "",
        author: { name: "Emma", username: "emma", profile: "" },
        stats: { likes: 167, comments: 12, views: "1.5K" },
        readTime: "5 min read",
        createdAt: "31 Jul 2026"
    },
    {
        id: 7,
        title: "Top Fashion Trends This Season",
        description: "Explore the latest fashion trends loved by designers worldwide.",
        category: "Fashion",
        image: "",
        author: { name: "Ava", username: "ava", profile: "" },
        stats: { likes: 276, comments: 31, views: "2.9K" },
        readTime: "5 min read",
        createdAt: "30 Jul 2026"
    },
    {
        id: 8,
        title: "Easy Recipes for Busy People",
        description: "Quick recipes that are healthy and delicious for everyday life.",
        category: "Food",
        image: "",
        author: { name: "Mason", username: "mason", profile: "" },
        stats: { likes: 143, comments: 19, views: "1.4K" },
        readTime: "4 min read",
        createdAt: "29 Jul 2026"
    },
    {
        id: 9,
        title: "Best Movies You Should Watch",
        description: "A collection of unforgettable movies from different genres.",
        category: "Movies",
        image: "",
        author: { name: "Lucas", username: "lucas", profile: "" },
        stats: { likes: 386, comments: 42, views: "4.1K" },
        readTime: "6 min read",
        createdAt: "28 Jul 2026"
    },
    {
        id: 10,
        title: "Daily Fitness Routine at Home",
        description: "Stay fit without going to the gym using these simple exercises.",
        category: "Health",
        image: "",
        author: { name: "Charlotte", username: "charlotte", profile: "" },
        stats: { likes: 211, comments: 23, views: "2.1K" },
        readTime: "5 min read",
        createdAt: "27 Jul 2026"
    },
    {
        id: 11,
        title: "The Rise of Electric Vehicles",
        description: "Electric cars are changing the future of transportation.",
        category: "Technology",
        image: "",
        author: { name: "Benjamin", username: "benjamin", profile: "" },
        stats: { likes: 354, comments: 27, views: "3.8K" },
        readTime: "6 min read",
        createdAt: "26 Jul 2026"
    },
    {
        id: 12,
        title: "Travel Guide to Switzerland",
        description: "Everything you need to know before visiting Switzerland.",
        category: "Travel",
        image: "",
        author: { name: "Harper", username: "harper", profile: "" },
        stats: { likes: 301, comments: 35, views: "3.1K" },
        readTime: "8 min read",
        createdAt: "25 Jul 2026"
    },
    {
        id: 13,
        title: "Football Players to Watch",
        description: "Top football stars making headlines this season.",
        category: "Sports",
        image: "",
        author: { name: "Daniel", username: "daniel", profile: "" },
        stats: { likes: 460, comments: 59, views: "5.2K" },
        readTime: "4 min read",
        createdAt: "24 Jul 2026"
    },
    {
        id: 14,
        title: "Minimalist Lifestyle Benefits",
        description: "Living with less can make your life more meaningful.",
        category: "Lifestyle",
        image: "",
        author: { name: "Emily", username: "emily", profile: "" },
        stats: { likes: 219, comments: 16, views: "2.2K" },
        readTime: "5 min read",
        createdAt: "23 Jul 2026"
    },
    {
        id: 15,
        title: "Photography Tips for Beginners",
        description: "Master your camera with these simple photography tips.",
        category: "Photography",
        image: "",
        author: { name: "Michael", username: "michael", profile: "" },
        stats: { likes: 334, comments: 41, views: "3.5K" },
        readTime: "7 min read",
        createdAt: "22 Jul 2026"
    },
    {
        id: 16,
        title: "How to Save Money Every Month",
        description: "Simple finance tricks that actually work.",
        category: "Finance",
        image: "",
        author: { name: "William", username: "william", profile: "" },
        stats: { likes: 198, comments: 18, views: "2.0K" },
        readTime: "6 min read",
        createdAt: "21 Jul 2026"
    },
    {
        id: 17,
        title: "Top Programming Languages",
        description: "The best programming languages to learn this year.",
        category: "Technology",
        image: "",
        author: { name: "Alexander", username: "alex", profile: "" },
        stats: { likes: 489, comments: 72, views: "5.9K" },
        readTime: "9 min read",
        createdAt: "20 Jul 2026"
    },
    {
        id: 18,
        title: "Morning Routine for Success",
        description: "Start your day with habits that boost productivity.",
        category: "Lifestyle",
        image: "",
        author: { name: "Ella", username: "ella", profile: "" },
        stats: { likes: 177, comments: 13, views: "1.8K" },
        readTime: "4 min read",
        createdAt: "19 Jul 2026"
    },
    {
        id: 19,
        title: "Latest Smartphone Review",
        description: "A detailed review of this year's most popular smartphone.",
        category: "Technology",
        image: "",
        author: { name: "Logan", username: "logan", profile: "" },
        stats: { likes: 410, comments: 48, views: "4.7K" },
        readTime: "6 min read",
        createdAt: "18 Jul 2026"
    },
    {
        id: 20,
        title: "Street Food Around the World",
        description: "Taste the most famous street foods from different countries.",
        category: "Food",
        image: "",
        author: { name: "Grace", username: "grace", profile: "" },
        stats: { likes: 254, comments: 24, views: "2.6K" },
        readTime: "5 min read",
        createdAt: "17 Jul 2026"
    },
    {
        id: 21,
        title: "Upcoming Web Series to Watch",
        description: "Exciting web series releasing this month.",
        category: "Entertainment",
        image: "",
        author: { name: "Henry", username: "henry", profile: "" },
        stats: { likes: 298, comments: 33, views: "3.0K" },
        readTime: "5 min read",
        createdAt: "16 Jul 2026"
    },
    {
        id: 22,
        title: "History's Greatest Empires",
        description: "Explore the rise and fall of powerful civilizations.",
        category: "History",
        image: "",
        author: { name: "Lily", username: "lily", profile: "" },
        stats: { likes: 185, comments: 17, views: "2.1K" },
        readTime: "8 min read",
        createdAt: "15 Jul 2026"
    },
    {
        id: 23,
        title: "The Science Behind Sleep",
        description: "Understand why quality sleep is essential for health.",
        category: "Science",
        image: "",
        author: { name: "Jack", username: "jack", profile: "" },
        stats: { likes: 263, comments: 22, views: "2.8K" },
        readTime: "5 min read",
        createdAt: "14 Jul 2026"
    },
    {
        id: 24,
        title: "Best Budget Laptops",
        description: "Affordable laptops for students and professionals.",
        category: "Technology",
        image: "",
        author: { name: "Scarlett", username: "scarlett", profile: "" },
        stats: { likes: 321, comments: 30, views: "3.4K" },
        readTime: "6 min read",
        createdAt: "13 Jul 2026"
    },
    {
        id: 25,
        title: "How to Start Freelancing",
        description: "A beginner's guide to earning online as a freelancer.",
        category: "Business",
        image: "",
        author: { name: "David", username: "david", profile: "" },
        stats: { likes: 392, comments: 46, views: "4.3K" },
        readTime: "7 min read",
        createdAt: "12 Jul 2026"
    },
    {
        id: 26,
        title: "The Beauty of Nature Photography",
        description: "Capture breathtaking landscapes like a professional.",
        category: "Photography",
        image: "",
        author: { name: "Victoria", username: "victoria", profile: "" },
        stats: { likes: 214, comments: 20, views: "2.3K" },
        readTime: "5 min read",
        createdAt: "11 Jul 2026"
    },
    {
        id: 27,
        title: "Top 10 Anime of All Time",
        description: "A must-watch list for every anime lover.",
        category: "Entertainment",
        image: "",
        author: { name: "Samuel", username: "samuel", profile: "" },
        stats: { likes: 505, comments: 82, views: "6.4K" },
        readTime: "8 min read",
        createdAt: "10 Jul 2026"
    },
    {
        id: 28,
        title: "Home Decoration Ideas",
        description: "Creative home decoration ideas on a small budget.",
        category: "Lifestyle",
        image: "",
        author: { name: "Chloe", username: "chloe", profile: "" },
        stats: { likes: 176, comments: 11, views: "1.9K" },
        readTime: "4 min read",
        createdAt: "09 Jul 2026"
    },
    {
        id: 29,
        title: "Future of Space Exploration",
        description: "How humans are preparing for life beyond Earth.",
        category: "Science",
        image: "",
        author: { name: "Joseph", username: "joseph", profile: "" },
        stats: { likes: 441, comments: 55, views: "5.0K" },
        readTime: "7 min read",
        createdAt: "08 Jul 2026"
    },
    {
        id: 30,
        title: "Top Books Everyone Should Read",
        description: "Classic and modern books that inspire every reader.",
        category: "Books",
        image: "",
        author: { name: "Natalie", username: "natalie", profile: "" },
        stats: { likes: 287, comments: 29, views: "3.1K" },
        readTime: "6 min read",
        createdAt: "07 Jul 2026"
    }
];

export default blog_data;